### ISSUE TITLE
R610 Issues.

### ISSUE THREAD

**Issue by akxks** [hippyod/dell-idrac-6-fan-speed-control-service#1]
Hi, this does not work. it constantly says 0x00 at the end in Htop
The idrac ip is correct, username and password is correct, 

So im not sure why its not working. ?
Idrac ip is 192.168.0.87 whereas the server is 192.168.0.86 

Server is still loud

When watching fan-speed-control.service it says permission denied ??

**Comment by ExenalEurope** [comment]
Even 0xFF or any other value, does not change the Server Fan Speed ? hm... im confused

**Comment by hippyod** [comment]
A) Have you run ipmitool from the command line to confirm you can connect and get a list of commands?  For example

`ipmitool -I lanplus -H 192.168.1.200 -U root -P calvin`

B) When you installed the script (fan-speed-control.sh), did you remember to make it  executable?  That sounds like the permission denied issue, without knowing anything else.

**Comment by akxks** [comment]
I think that my problem is that

I have one ethernet cable plugged into the Server, and if i plug it into the idrac port, then the server wont have internet,
but if i plug it into one of the other ports (that doesnt support idrac) but then it will have access to the internet.

So i need 2 ethernet cables plugged into the server, which is hard to do because this contraption is upstairs.
Any suggestions? It cant establish a session, now I understand... because both ports need internet access but its hard to do that right now

**Comment by hippyod** [comment]
Whatever cable you're running upstairs, get a cheap ethernet switch.  That's how all my stuff is connected.

**Comment by akxks** [comment]
So you plug one internet cable into it , and all the 5 ports can be shared, cool! I will get one, how well does the R610 fan script work though ? Did it work for you ? And idle, with nothing on, is it fully quiet ? Wouldnt that be hex 0xFF, it doesnt mention it in your code.

I just got the switch, hope to see the script work otherwise I would be sad I wasted money. I don't see why at 25 degrees Celsius, the fans should be running, it was 65 decibels, when I was running it and testing it.

**Comment by akxks** [comment]
?? How good is this script

**Comment by hippyod** [comment]
I've been running this script as a service continuously for more than six months now.  My R610 is my go-to dev server for my other projects.  I don't even think about this project most of the time anymore, and the only reason I remember it is when I reboot my server and the fans make my office unbearable until it kicks in.
